# Generated by Django 3.0.14 on 2022-01-15 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('number', models.CharField(max_length=4, unique=True)),
                ('slug', models.SlugField(max_length=256, unique=True)),
                ('departure_time', models.DateTimeField()),
                ('destination', models.CharField(max_length=250)),
                ('available_seats', models.PositiveIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('not_available', 'Not Available')], default='available', max_length=15)),
            ],
            options={
                'verbose_name': 'Bus',
                'verbose_name_plural': 'Buses',
                'ordering': ('-available_seats',),
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('number', models.PositiveIntegerField(unique=True)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('booked_seats', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, default=5.0, max_digits=19)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='brs.Bus')),
            ],
        ),
    ]
