# Generated by Django 3.0.14 on 2022-01-15 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brs', '0002_auto_20220115_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='slug',
            field=models.SlugField(max_length=512, unique=True),
        ),
    ]
