# Generated by Django 3.0.14 on 2022-01-15 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brs', '0002_remove_bus_total_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='number',
            field=models.CharField(max_length=4, unique=True),
        ),
    ]
