# Generated by Django 3.0.14 on 2022-01-15 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brs', '0003_auto_20220115_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='slug',
            field=models.SlugField(max_length=256, unique=True),
        ),
    ]
